### ISSUE TITLE
While Firefox in hide title bar mod , we can not move window

### ISSUE THREAD

**Issue by ghost** [vlastavesely/raleigh-reloaded#6]
with newly firefox version , we can set "hide title bar " in custom,but  after that, i cant move firefox by hold mouse down at the blank space  near the first or last tags.and  original raleigh can,can you "fixed" it in reload version.
mabe  this  is firefox issue for they change ui  and i haven found other soft with this  issue

**Comment by vlastavesely** [comment]
I do not think it is theme-related. The UI of the window is just not programmed for dragging without title bar.

**Comment by ghost** [comment]
it is progammed drigging wiithout title bar.i can do it with other theme ,and i have test again ,the original raleigh can

**Comment by vlastavesely** [comment]
What is version of your Firefox do you use? Where the "hide title bar" can be set?

**Comment by ghost** [comment]
https://imgur.com/19mBd5Vl.png . late for response . i mean firefox 57+  in custom  uncheck titlebar

**Comment by vlastavesely** [comment]
Ok, I think I know what did you mean. I will check what can be done about it.

**Comment by vlastavesely** [comment]
It should be fixed now.

**Comment by ghost** [comment]
seems   gtk2 part still have the issue,and some info:

<pre><font color="#FFFFFF"><b>  ,g$$P&quot;     &quot;&quot;&quot;Y$$.&quot;.</b></font>        <font color="#FF5555"><b>OS</b></font>: Debian GNU/Linux buster/sid x86_64 
<font color="#FFFFFF"><b> ,$$P&apos;              `$$$.</b></font>     <font color="#FF5555"><b>Kernel</b></font>: 4.19.0-1-amd64 
<font color="#FFFFFF"><b>&apos;,$$P       ,ggs.     `$$b:</b></font>   <font color="#FF5555"><b>Uptime</b></font>: 2 hours, 56 mins 
<font color="#FFFFFF"><b>`d$$&apos;     ,$P&quot;&apos;   </b></font><font color="#FF5555"><b>.</b></font><font color="#FFFFFF"><b>    $$$</b></font>    <font color="#FF5555"><b>Packages</b></font>: 1647 (dpkg) 
<font color="#FFFFFF"><b> $$P      d$&apos;     </b></font><font color="#FF5555"><b>,</b></font><font color="#FFFFFF"><b>    $$P</b></font>    <font color="#FF5555"><b>Shell</b></font>: bash 4.4.23 
<font color="#FFFFFF"><b> $$:      $$.   </b></font><font color="#FF5555"><b>-</b></font><font color="#FFFFFF"><b>    ,d$$&apos;</b></font>    <font color="#FF5555"><b>Resolution</b></font>: 1920x1080 
<font color="#FFFFFF"><b> $$;      Y$b._   _,d$P&apos;</b></font>      <font color="#FF5555"><b>DE</b></font>: Xfce 
<font color="#FFFFFF"><b> Y$$.    </b></font><font color="#FF5555"><b>`.</b></font><font color="#FFFFFF"><b>`&quot;Y$$$$P&quot;&apos;</b></font>         <font color="#FF5555"><b>WM</b></font>: Xfwm4 
<font color="#FFFFFF"><b> `$$b      </b></font><font color="#FF5555"><b>&quot;-.__</b></font>              <font color="#FF5555"><b>WM Theme</b></font>: Qogir-light 
<font color="#FFFFFF"><b>  `Y$$</b></font>                        <font color="#FF5555"><b>Theme</b></font>: src [GTK2] 
<font color="#FFFFFF"><b>   `Y$$.</b></font>                      <font color="#FF5555"><b>Icons</b></font>: Numix-White [GTK2] 
<font color="#FFFFFF"><b>     `$$b.</b></font>                    <font color="#FF5555"><b>Terminal</b></font>: xfce4-terminal 
<font color="#FFFFFF"><b>       `Y$$b.</b></font>                 <font color="#FF5555"><b>Terminal Font</b></font>: Monospace 12 
<font color="#FFFFFF"><b>          `&quot;Y$b._</b></font>             <font color="#FF5555"><b>CPU</b></font>: Intel i5-4590 (4) @ 3.700GHz 
<font color="#FFFFFF"><b>              `&quot;&quot;&quot;</b></font>            <font color="#FF5555"><b>GPU</b></font>: NVIDIA GeForce GTX 750 Ti 
                              <font color="#FF5555"><b>Memory</b></font>: 2534MiB / 15960MiB 
</pre>

**Comment by vlastavesely** [comment]
Raleigh is the default theme of GTK2. Raleigh-Reloaded does not define any custom properties to override the original GTK2 theme and since GTK2 is very old, I do not see any reason for making any changes on it.

Do you use any GTK2 application in your day-to-day life that causes problems to you? If not, I close this issue without any changes on GTK2 version of the theme. :)
